### ISSUE TITLE
Take th nonsns from @akemmanuel

### ISSUE THREAD

**Issue by carlosmintfan** [LitoMore/honeypotoberfest#12]
My friend has a nonsense repo (see heading( I hpe you can coppy the code grom. But it unfortunazely has no licemse file so we very saddely have to wait until I have arreglated that with him.

**Comment by carlosmintfan** [comment]
https://github.com/akemmanuel/Nonsense/pull/1 :((:(

**Comment by LitoMore** [comment]
Trolling is fine but no spamming.

**Comment by carlosmintfan** [comment]
> Trolling is fine but no spamming.

Sorry, what? Just copy the Nonsense from him – oh, I will make a PR.
